# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from cabin_msgs/Imu.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class Imu(genpy.Message):
  _md5sum = "d2d61ea9f9d4eb67310c1b993d18ccc2"
  _type = "cabin_msgs/Imu"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header
geometry_msgs/Quaternion quaternion # From Inertial frame to Body frame
geometry_msgs/Vector3 rpy_rad # [rad]
geometry_msgs/Vector3 rpy_deg # [deg]
float64 heading_alt # [deg]
float64 heading_LORD # [deg]
geometry_msgs/Vector3 linear_accel # [m/s^2]
geometry_msgs/Vector3 ang_vel_rad # [rad/s]
geometry_msgs/Vector3 ang_vel_deg # [deg/s]
geometry_msgs/Vector3 ang_accel_rad # [rad/s]
geometry_msgs/Vector3 ang_accel_deg # [deg/s]
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['header','quaternion','rpy_rad','rpy_deg','heading_alt','heading_LORD','linear_accel','ang_vel_rad','ang_vel_deg','ang_accel_rad','ang_accel_deg']
  _slot_types = ['std_msgs/Header','geometry_msgs/Quaternion','geometry_msgs/Vector3','geometry_msgs/Vector3','float64','float64','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,quaternion,rpy_rad,rpy_deg,heading_alt,heading_LORD,linear_accel,ang_vel_rad,ang_vel_deg,ang_accel_rad,ang_accel_deg

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Imu, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.quaternion is None:
        self.quaternion = geometry_msgs.msg.Quaternion()
      if self.rpy_rad is None:
        self.rpy_rad = geometry_msgs.msg.Vector3()
      if self.rpy_deg is None:
        self.rpy_deg = geometry_msgs.msg.Vector3()
      if self.heading_alt is None:
        self.heading_alt = 0.
      if self.heading_LORD is None:
        self.heading_LORD = 0.
      if self.linear_accel is None:
        self.linear_accel = geometry_msgs.msg.Vector3()
      if self.ang_vel_rad is None:
        self.ang_vel_rad = geometry_msgs.msg.Vector3()
      if self.ang_vel_deg is None:
        self.ang_vel_deg = geometry_msgs.msg.Vector3()
      if self.ang_accel_rad is None:
        self.ang_accel_rad = geometry_msgs.msg.Vector3()
      if self.ang_accel_deg is None:
        self.ang_accel_deg = geometry_msgs.msg.Vector3()
    else:
      self.header = std_msgs.msg.Header()
      self.quaternion = geometry_msgs.msg.Quaternion()
      self.rpy_rad = geometry_msgs.msg.Vector3()
      self.rpy_deg = geometry_msgs.msg.Vector3()
      self.heading_alt = 0.
      self.heading_LORD = 0.
      self.linear_accel = geometry_msgs.msg.Vector3()
      self.ang_vel_rad = geometry_msgs.msg.Vector3()
      self.ang_vel_deg = geometry_msgs.msg.Vector3()
      self.ang_accel_rad = geometry_msgs.msg.Vector3()
      self.ang_accel_deg = geometry_msgs.msg.Vector3()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_27d().pack(_x.quaternion.x, _x.quaternion.y, _x.quaternion.z, _x.quaternion.w, _x.rpy_rad.x, _x.rpy_rad.y, _x.rpy_rad.z, _x.rpy_deg.x, _x.rpy_deg.y, _x.rpy_deg.z, _x.heading_alt, _x.heading_LORD, _x.linear_accel.x, _x.linear_accel.y, _x.linear_accel.z, _x.ang_vel_rad.x, _x.ang_vel_rad.y, _x.ang_vel_rad.z, _x.ang_vel_deg.x, _x.ang_vel_deg.y, _x.ang_vel_deg.z, _x.ang_accel_rad.x, _x.ang_accel_rad.y, _x.ang_accel_rad.z, _x.ang_accel_deg.x, _x.ang_accel_deg.y, _x.ang_accel_deg.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.quaternion is None:
        self.quaternion = geometry_msgs.msg.Quaternion()
      if self.rpy_rad is None:
        self.rpy_rad = geometry_msgs.msg.Vector3()
      if self.rpy_deg is None:
        self.rpy_deg = geometry_msgs.msg.Vector3()
      if self.linear_accel is None:
        self.linear_accel = geometry_msgs.msg.Vector3()
      if self.ang_vel_rad is None:
        self.ang_vel_rad = geometry_msgs.msg.Vector3()
      if self.ang_vel_deg is None:
        self.ang_vel_deg = geometry_msgs.msg.Vector3()
      if self.ang_accel_rad is None:
        self.ang_accel_rad = geometry_msgs.msg.Vector3()
      if self.ang_accel_deg is None:
        self.ang_accel_deg = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 216
      (_x.quaternion.x, _x.quaternion.y, _x.quaternion.z, _x.quaternion.w, _x.rpy_rad.x, _x.rpy_rad.y, _x.rpy_rad.z, _x.rpy_deg.x, _x.rpy_deg.y, _x.rpy_deg.z, _x.heading_alt, _x.heading_LORD, _x.linear_accel.x, _x.linear_accel.y, _x.linear_accel.z, _x.ang_vel_rad.x, _x.ang_vel_rad.y, _x.ang_vel_rad.z, _x.ang_vel_deg.x, _x.ang_vel_deg.y, _x.ang_vel_deg.z, _x.ang_accel_rad.x, _x.ang_accel_rad.y, _x.ang_accel_rad.z, _x.ang_accel_deg.x, _x.ang_accel_deg.y, _x.ang_accel_deg.z,) = _get_struct_27d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_27d().pack(_x.quaternion.x, _x.quaternion.y, _x.quaternion.z, _x.quaternion.w, _x.rpy_rad.x, _x.rpy_rad.y, _x.rpy_rad.z, _x.rpy_deg.x, _x.rpy_deg.y, _x.rpy_deg.z, _x.heading_alt, _x.heading_LORD, _x.linear_accel.x, _x.linear_accel.y, _x.linear_accel.z, _x.ang_vel_rad.x, _x.ang_vel_rad.y, _x.ang_vel_rad.z, _x.ang_vel_deg.x, _x.ang_vel_deg.y, _x.ang_vel_deg.z, _x.ang_accel_rad.x, _x.ang_accel_rad.y, _x.ang_accel_rad.z, _x.ang_accel_deg.x, _x.ang_accel_deg.y, _x.ang_accel_deg.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.quaternion is None:
        self.quaternion = geometry_msgs.msg.Quaternion()
      if self.rpy_rad is None:
        self.rpy_rad = geometry_msgs.msg.Vector3()
      if self.rpy_deg is None:
        self.rpy_deg = geometry_msgs.msg.Vector3()
      if self.linear_accel is None:
        self.linear_accel = geometry_msgs.msg.Vector3()
      if self.ang_vel_rad is None:
        self.ang_vel_rad = geometry_msgs.msg.Vector3()
      if self.ang_vel_deg is None:
        self.ang_vel_deg = geometry_msgs.msg.Vector3()
      if self.ang_accel_rad is None:
        self.ang_accel_rad = geometry_msgs.msg.Vector3()
      if self.ang_accel_deg is None:
        self.ang_accel_deg = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 216
      (_x.quaternion.x, _x.quaternion.y, _x.quaternion.z, _x.quaternion.w, _x.rpy_rad.x, _x.rpy_rad.y, _x.rpy_rad.z, _x.rpy_deg.x, _x.rpy_deg.y, _x.rpy_deg.z, _x.heading_alt, _x.heading_LORD, _x.linear_accel.x, _x.linear_accel.y, _x.linear_accel.z, _x.ang_vel_rad.x, _x.ang_vel_rad.y, _x.ang_vel_rad.z, _x.ang_vel_deg.x, _x.ang_vel_deg.y, _x.ang_vel_deg.z, _x.ang_accel_rad.x, _x.ang_accel_rad.y, _x.ang_accel_rad.z, _x.ang_accel_deg.x, _x.ang_accel_deg.y, _x.ang_accel_deg.z,) = _get_struct_27d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_27d = None
def _get_struct_27d():
    global _struct_27d
    if _struct_27d is None:
        _struct_27d = struct.Struct("<27d")
    return _struct_27d
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
