# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from cabin_msgs/Thrust.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Thrust(genpy.Message):
  _md5sum = "b32a790aa38ecc6d0210e752292519c8"
  _type = "cabin_msgs/Thrust"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 vector_port_fwd
float32 vector_stbd_fwd
float32 vector_port_aft
float32 vector_stbd_aft
float32 heave_port_fwd
float32 heave_stbd_fwd
float32 heave_port_aft
float32 heave_stbd_aft

# Used to index controllers within the pwm controller
int8 VPF = 0
int8 VSF = 1
int8 VPA = 2
int8 VSA = 3
int8 HPF = 4
int8 HSF = 5
int8 HPA = 6
int8 HSA = 7"""
  # Pseudo-constants
  VPF = 0
  VSF = 1
  VPA = 2
  VSA = 3
  HPF = 4
  HSF = 5
  HPA = 6
  HSA = 7

  __slots__ = ['vector_port_fwd','vector_stbd_fwd','vector_port_aft','vector_stbd_aft','heave_port_fwd','heave_stbd_fwd','heave_port_aft','heave_stbd_aft']
  _slot_types = ['float32','float32','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       vector_port_fwd,vector_stbd_fwd,vector_port_aft,vector_stbd_aft,heave_port_fwd,heave_stbd_fwd,heave_port_aft,heave_stbd_aft

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Thrust, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.vector_port_fwd is None:
        self.vector_port_fwd = 0.
      if self.vector_stbd_fwd is None:
        self.vector_stbd_fwd = 0.
      if self.vector_port_aft is None:
        self.vector_port_aft = 0.
      if self.vector_stbd_aft is None:
        self.vector_stbd_aft = 0.
      if self.heave_port_fwd is None:
        self.heave_port_fwd = 0.
      if self.heave_stbd_fwd is None:
        self.heave_stbd_fwd = 0.
      if self.heave_port_aft is None:
        self.heave_port_aft = 0.
      if self.heave_stbd_aft is None:
        self.heave_stbd_aft = 0.
    else:
      self.vector_port_fwd = 0.
      self.vector_stbd_fwd = 0.
      self.vector_port_aft = 0.
      self.vector_stbd_aft = 0.
      self.heave_port_fwd = 0.
      self.heave_stbd_fwd = 0.
      self.heave_port_aft = 0.
      self.heave_stbd_aft = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_8f().pack(_x.vector_port_fwd, _x.vector_stbd_fwd, _x.vector_port_aft, _x.vector_stbd_aft, _x.heave_port_fwd, _x.heave_stbd_fwd, _x.heave_port_aft, _x.heave_stbd_aft))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.vector_port_fwd, _x.vector_stbd_fwd, _x.vector_port_aft, _x.vector_stbd_aft, _x.heave_port_fwd, _x.heave_stbd_fwd, _x.heave_port_aft, _x.heave_stbd_aft,) = _get_struct_8f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_8f().pack(_x.vector_port_fwd, _x.vector_stbd_fwd, _x.vector_port_aft, _x.vector_stbd_aft, _x.heave_port_fwd, _x.heave_stbd_fwd, _x.heave_port_aft, _x.heave_stbd_aft))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.vector_port_fwd, _x.vector_stbd_fwd, _x.vector_port_aft, _x.vector_stbd_aft, _x.heave_port_fwd, _x.heave_stbd_fwd, _x.heave_port_aft, _x.heave_stbd_aft,) = _get_struct_8f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_8f = None
def _get_struct_8f():
    global _struct_8f
    if _struct_8f is None:
        _struct_8f = struct.Struct("<8f")
    return _struct_8f
