// Generated by gencpp from file cabin_msgs/AttitudeCommand.msg
// DO NOT EDIT!


#ifndef CABIN_MSGS_MESSAGE_ATTITUDECOMMAND_H
#define CABIN_MSGS_MESSAGE_ATTITUDECOMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cabin_msgs
{
template <class ContainerAllocator>
struct AttitudeCommand_
{
  typedef AttitudeCommand_<ContainerAllocator> Type;

  AttitudeCommand_()
    : value(0.0)
    , mode(0)  {
    }
  AttitudeCommand_(const ContainerAllocator& _alloc)
    : value(0.0)
    , mode(0)  {
  (void)_alloc;
    }



   typedef float _value_type;
  _value_type value;

   typedef int8_t _mode_type;
  _mode_type mode;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(POSITION)
  #undef POSITION
#endif
#if defined(_WIN32) && defined(VELOCITY)
  #undef VELOCITY
#endif
#if defined(_WIN32) && defined(MOMENT)
  #undef MOMENT
#endif

  enum {
    POSITION = 0,
    VELOCITY = 1,
    MOMENT = 2,
  };


  typedef boost::shared_ptr< ::cabin_msgs::AttitudeCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cabin_msgs::AttitudeCommand_<ContainerAllocator> const> ConstPtr;

}; // struct AttitudeCommand_

typedef ::cabin_msgs::AttitudeCommand_<std::allocator<void> > AttitudeCommand;

typedef boost::shared_ptr< ::cabin_msgs::AttitudeCommand > AttitudeCommandPtr;
typedef boost::shared_ptr< ::cabin_msgs::AttitudeCommand const> AttitudeCommandConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cabin_msgs::AttitudeCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cabin_msgs::AttitudeCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cabin_msgs::AttitudeCommand_<ContainerAllocator1> & lhs, const ::cabin_msgs::AttitudeCommand_<ContainerAllocator2> & rhs)
{
  return lhs.value == rhs.value &&
    lhs.mode == rhs.mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cabin_msgs::AttitudeCommand_<ContainerAllocator1> & lhs, const ::cabin_msgs::AttitudeCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cabin_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cabin_msgs::AttitudeCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cabin_msgs::AttitudeCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cabin_msgs::AttitudeCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cabin_msgs::AttitudeCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cabin_msgs::AttitudeCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cabin_msgs::AttitudeCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cabin_msgs::AttitudeCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e78c3e439ccf2c96eaea9d7a49cd863a";
  }

  static const char* value(const ::cabin_msgs::AttitudeCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe78c3e439ccf2c96ULL;
  static const uint64_t static_value2 = 0xeaea9d7a49cd863aULL;
};

template<class ContainerAllocator>
struct DataType< ::cabin_msgs::AttitudeCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cabin_msgs/AttitudeCommand";
  }

  static const char* value(const ::cabin_msgs::AttitudeCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cabin_msgs::AttitudeCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 value\n"
"int8 mode\n"
"\n"
"int8 POSITION=0\n"
"int8 VELOCITY=1\n"
"int8 MOMENT=2\n"
;
  }

  static const char* value(const ::cabin_msgs::AttitudeCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cabin_msgs::AttitudeCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.value);
      stream.next(m.mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AttitudeCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cabin_msgs::AttitudeCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cabin_msgs::AttitudeCommand_<ContainerAllocator>& v)
  {
    s << indent << "value: ";
    Printer<float>::stream(s, indent + "  ", v.value);
    s << indent << "mode: ";
    Printer<int8_t>::stream(s, indent + "  ", v.mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CABIN_MSGS_MESSAGE_ATTITUDECOMMAND_H
