// Generated by gencpp from file cabin_msgs/ControlStatus.msg
// DO NOT EDIT!


#ifndef CABIN_MSGS_MESSAGE_CONTROLSTATUS_H
#define CABIN_MSGS_MESSAGE_CONTROLSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace cabin_msgs
{
template <class ContainerAllocator>
struct ControlStatus_
{
  typedef ControlStatus_<ContainerAllocator> Type;

  ControlStatus_()
    : header()
    , reference(0.0)
    , current(0.0)
    , error(0.0)  {
    }
  ControlStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , reference(0.0)
    , current(0.0)
    , error(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _reference_type;
  _reference_type reference;

   typedef double _current_type;
  _current_type current;

   typedef double _error_type;
  _error_type error;





  typedef boost::shared_ptr< ::cabin_msgs::ControlStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cabin_msgs::ControlStatus_<ContainerAllocator> const> ConstPtr;

}; // struct ControlStatus_

typedef ::cabin_msgs::ControlStatus_<std::allocator<void> > ControlStatus;

typedef boost::shared_ptr< ::cabin_msgs::ControlStatus > ControlStatusPtr;
typedef boost::shared_ptr< ::cabin_msgs::ControlStatus const> ControlStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cabin_msgs::ControlStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cabin_msgs::ControlStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cabin_msgs::ControlStatus_<ContainerAllocator1> & lhs, const ::cabin_msgs::ControlStatus_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.reference == rhs.reference &&
    lhs.current == rhs.current &&
    lhs.error == rhs.error;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cabin_msgs::ControlStatus_<ContainerAllocator1> & lhs, const ::cabin_msgs::ControlStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cabin_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cabin_msgs::ControlStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cabin_msgs::ControlStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cabin_msgs::ControlStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cabin_msgs::ControlStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cabin_msgs::ControlStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cabin_msgs::ControlStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cabin_msgs::ControlStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "36822de25dac417a564a43be1675e833";
  }

  static const char* value(const ::cabin_msgs::ControlStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x36822de25dac417aULL;
  static const uint64_t static_value2 = 0x564a43be1675e833ULL;
};

template<class ContainerAllocator>
struct DataType< ::cabin_msgs::ControlStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cabin_msgs/ControlStatus";
  }

  static const char* value(const ::cabin_msgs::ControlStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cabin_msgs::ControlStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"float64 reference\n"
"float64 current\n"
"float64 error\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::cabin_msgs::ControlStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cabin_msgs::ControlStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.reference);
      stream.next(m.current);
      stream.next(m.error);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControlStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cabin_msgs::ControlStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cabin_msgs::ControlStatus_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "reference: ";
    Printer<double>::stream(s, indent + "  ", v.reference);
    s << indent << "current: ";
    Printer<double>::stream(s, indent + "  ", v.current);
    s << indent << "error: ";
    Printer<double>::stream(s, indent + "  ", v.error);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CABIN_MSGS_MESSAGE_CONTROLSTATUS_H
