// Generated by gencpp from file cabin_msgs/DepthCommand.msg
// DO NOT EDIT!


#ifndef CABIN_MSGS_MESSAGE_DEPTHCOMMAND_H
#define CABIN_MSGS_MESSAGE_DEPTHCOMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cabin_msgs
{
template <class ContainerAllocator>
struct DepthCommand_
{
  typedef DepthCommand_<ContainerAllocator> Type;

  DepthCommand_()
    : active(false)
    , depth(0.0)  {
    }
  DepthCommand_(const ContainerAllocator& _alloc)
    : active(false)
    , depth(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _active_type;
  _active_type active;

   typedef float _depth_type;
  _depth_type depth;





  typedef boost::shared_ptr< ::cabin_msgs::DepthCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cabin_msgs::DepthCommand_<ContainerAllocator> const> ConstPtr;

}; // struct DepthCommand_

typedef ::cabin_msgs::DepthCommand_<std::allocator<void> > DepthCommand;

typedef boost::shared_ptr< ::cabin_msgs::DepthCommand > DepthCommandPtr;
typedef boost::shared_ptr< ::cabin_msgs::DepthCommand const> DepthCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cabin_msgs::DepthCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cabin_msgs::DepthCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cabin_msgs::DepthCommand_<ContainerAllocator1> & lhs, const ::cabin_msgs::DepthCommand_<ContainerAllocator2> & rhs)
{
  return lhs.active == rhs.active &&
    lhs.depth == rhs.depth;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cabin_msgs::DepthCommand_<ContainerAllocator1> & lhs, const ::cabin_msgs::DepthCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cabin_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cabin_msgs::DepthCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cabin_msgs::DepthCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cabin_msgs::DepthCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cabin_msgs::DepthCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cabin_msgs::DepthCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cabin_msgs::DepthCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cabin_msgs::DepthCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5e1e60925f231c53d2a73e74a385e633";
  }

  static const char* value(const ::cabin_msgs::DepthCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5e1e60925f231c53ULL;
  static const uint64_t static_value2 = 0xd2a73e74a385e633ULL;
};

template<class ContainerAllocator>
struct DataType< ::cabin_msgs::DepthCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cabin_msgs/DepthCommand";
  }

  static const char* value(const ::cabin_msgs::DepthCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cabin_msgs::DepthCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool active\n"
"float32 depth\n"
;
  }

  static const char* value(const ::cabin_msgs::DepthCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cabin_msgs::DepthCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.active);
      stream.next(m.depth);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DepthCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cabin_msgs::DepthCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cabin_msgs::DepthCommand_<ContainerAllocator>& v)
  {
    s << indent << "active: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.active);
    s << indent << "depth: ";
    Printer<float>::stream(s, indent + "  ", v.depth);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CABIN_MSGS_MESSAGE_DEPTHCOMMAND_H
