// Generated by gencpp from file cabin_msgs/Depth.msg
// DO NOT EDIT!


#ifndef CABIN_MSGS_MESSAGE_DEPTH_H
#define CABIN_MSGS_MESSAGE_DEPTH_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace cabin_msgs
{
template <class ContainerAllocator>
struct Depth_
{
  typedef Depth_<ContainerAllocator> Type;

  Depth_()
    : header()
    , depth(0.0)
    , pressure(0.0)
    , temp(0.0)
    , altitude(0.0)  {
    }
  Depth_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , depth(0.0)
    , pressure(0.0)
    , temp(0.0)
    , altitude(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _depth_type;
  _depth_type depth;

   typedef float _pressure_type;
  _pressure_type pressure;

   typedef float _temp_type;
  _temp_type temp;

   typedef float _altitude_type;
  _altitude_type altitude;





  typedef boost::shared_ptr< ::cabin_msgs::Depth_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cabin_msgs::Depth_<ContainerAllocator> const> ConstPtr;

}; // struct Depth_

typedef ::cabin_msgs::Depth_<std::allocator<void> > Depth;

typedef boost::shared_ptr< ::cabin_msgs::Depth > DepthPtr;
typedef boost::shared_ptr< ::cabin_msgs::Depth const> DepthConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cabin_msgs::Depth_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cabin_msgs::Depth_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cabin_msgs::Depth_<ContainerAllocator1> & lhs, const ::cabin_msgs::Depth_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.depth == rhs.depth &&
    lhs.pressure == rhs.pressure &&
    lhs.temp == rhs.temp &&
    lhs.altitude == rhs.altitude;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cabin_msgs::Depth_<ContainerAllocator1> & lhs, const ::cabin_msgs::Depth_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cabin_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cabin_msgs::Depth_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cabin_msgs::Depth_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cabin_msgs::Depth_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cabin_msgs::Depth_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cabin_msgs::Depth_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cabin_msgs::Depth_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cabin_msgs::Depth_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2c76628b896fd4724ce45a5b6b30d3bb";
  }

  static const char* value(const ::cabin_msgs::Depth_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2c76628b896fd472ULL;
  static const uint64_t static_value2 = 0x4ce45a5b6b30d3bbULL;
};

template<class ContainerAllocator>
struct DataType< ::cabin_msgs::Depth_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cabin_msgs/Depth";
  }

  static const char* value(const ::cabin_msgs::Depth_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cabin_msgs::Depth_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"float32 depth\n"
"float32 pressure\n"
"float32 temp\n"
"float32 altitude\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::cabin_msgs::Depth_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cabin_msgs::Depth_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.depth);
      stream.next(m.pressure);
      stream.next(m.temp);
      stream.next(m.altitude);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Depth_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cabin_msgs::Depth_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cabin_msgs::Depth_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "depth: ";
    Printer<float>::stream(s, indent + "  ", v.depth);
    s << indent << "pressure: ";
    Printer<float>::stream(s, indent + "  ", v.pressure);
    s << indent << "temp: ";
    Printer<float>::stream(s, indent + "  ", v.temp);
    s << indent << "altitude: ";
    Printer<float>::stream(s, indent + "  ", v.altitude);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CABIN_MSGS_MESSAGE_DEPTH_H
