// Generated by gencpp from file cabin_msgs/Imu.msg
// DO NOT EDIT!


#ifndef CABIN_MSGS_MESSAGE_IMU_H
#define CABIN_MSGS_MESSAGE_IMU_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Quaternion.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace cabin_msgs
{
template <class ContainerAllocator>
struct Imu_
{
  typedef Imu_<ContainerAllocator> Type;

  Imu_()
    : header()
    , quaternion()
    , rpy_rad()
    , rpy_deg()
    , heading_alt(0.0)
    , heading_LORD(0.0)
    , linear_accel()
    , ang_vel_rad()
    , ang_vel_deg()
    , ang_accel_rad()
    , ang_accel_deg()  {
    }
  Imu_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , quaternion(_alloc)
    , rpy_rad(_alloc)
    , rpy_deg(_alloc)
    , heading_alt(0.0)
    , heading_LORD(0.0)
    , linear_accel(_alloc)
    , ang_vel_rad(_alloc)
    , ang_vel_deg(_alloc)
    , ang_accel_rad(_alloc)
    , ang_accel_deg(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Quaternion_<ContainerAllocator>  _quaternion_type;
  _quaternion_type quaternion;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _rpy_rad_type;
  _rpy_rad_type rpy_rad;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _rpy_deg_type;
  _rpy_deg_type rpy_deg;

   typedef double _heading_alt_type;
  _heading_alt_type heading_alt;

   typedef double _heading_LORD_type;
  _heading_LORD_type heading_LORD;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _linear_accel_type;
  _linear_accel_type linear_accel;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _ang_vel_rad_type;
  _ang_vel_rad_type ang_vel_rad;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _ang_vel_deg_type;
  _ang_vel_deg_type ang_vel_deg;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _ang_accel_rad_type;
  _ang_accel_rad_type ang_accel_rad;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _ang_accel_deg_type;
  _ang_accel_deg_type ang_accel_deg;





  typedef boost::shared_ptr< ::cabin_msgs::Imu_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cabin_msgs::Imu_<ContainerAllocator> const> ConstPtr;

}; // struct Imu_

typedef ::cabin_msgs::Imu_<std::allocator<void> > Imu;

typedef boost::shared_ptr< ::cabin_msgs::Imu > ImuPtr;
typedef boost::shared_ptr< ::cabin_msgs::Imu const> ImuConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cabin_msgs::Imu_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cabin_msgs::Imu_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cabin_msgs::Imu_<ContainerAllocator1> & lhs, const ::cabin_msgs::Imu_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.quaternion == rhs.quaternion &&
    lhs.rpy_rad == rhs.rpy_rad &&
    lhs.rpy_deg == rhs.rpy_deg &&
    lhs.heading_alt == rhs.heading_alt &&
    lhs.heading_LORD == rhs.heading_LORD &&
    lhs.linear_accel == rhs.linear_accel &&
    lhs.ang_vel_rad == rhs.ang_vel_rad &&
    lhs.ang_vel_deg == rhs.ang_vel_deg &&
    lhs.ang_accel_rad == rhs.ang_accel_rad &&
    lhs.ang_accel_deg == rhs.ang_accel_deg;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cabin_msgs::Imu_<ContainerAllocator1> & lhs, const ::cabin_msgs::Imu_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cabin_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cabin_msgs::Imu_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cabin_msgs::Imu_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cabin_msgs::Imu_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cabin_msgs::Imu_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cabin_msgs::Imu_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cabin_msgs::Imu_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cabin_msgs::Imu_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d2d61ea9f9d4eb67310c1b993d18ccc2";
  }

  static const char* value(const ::cabin_msgs::Imu_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd2d61ea9f9d4eb67ULL;
  static const uint64_t static_value2 = 0x310c1b993d18ccc2ULL;
};

template<class ContainerAllocator>
struct DataType< ::cabin_msgs::Imu_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cabin_msgs/Imu";
  }

  static const char* value(const ::cabin_msgs::Imu_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cabin_msgs::Imu_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"geometry_msgs/Quaternion quaternion # From Inertial frame to Body frame\n"
"geometry_msgs/Vector3 rpy_rad # [rad]\n"
"geometry_msgs/Vector3 rpy_deg # [deg]\n"
"float64 heading_alt # [deg]\n"
"float64 heading_LORD # [deg]\n"
"geometry_msgs/Vector3 linear_accel # [m/s^2]\n"
"geometry_msgs/Vector3 ang_vel_rad # [rad/s]\n"
"geometry_msgs/Vector3 ang_vel_deg # [deg/s]\n"
"geometry_msgs/Vector3 ang_accel_rad # [rad/s]\n"
"geometry_msgs/Vector3 ang_accel_deg # [deg/s]\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::cabin_msgs::Imu_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cabin_msgs::Imu_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.quaternion);
      stream.next(m.rpy_rad);
      stream.next(m.rpy_deg);
      stream.next(m.heading_alt);
      stream.next(m.heading_LORD);
      stream.next(m.linear_accel);
      stream.next(m.ang_vel_rad);
      stream.next(m.ang_vel_deg);
      stream.next(m.ang_accel_rad);
      stream.next(m.ang_accel_deg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Imu_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cabin_msgs::Imu_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cabin_msgs::Imu_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "quaternion: ";
    s << std::endl;
    Printer< ::geometry_msgs::Quaternion_<ContainerAllocator> >::stream(s, indent + "  ", v.quaternion);
    s << indent << "rpy_rad: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.rpy_rad);
    s << indent << "rpy_deg: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.rpy_deg);
    s << indent << "heading_alt: ";
    Printer<double>::stream(s, indent + "  ", v.heading_alt);
    s << indent << "heading_LORD: ";
    Printer<double>::stream(s, indent + "  ", v.heading_LORD);
    s << indent << "linear_accel: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.linear_accel);
    s << indent << "ang_vel_rad: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.ang_vel_rad);
    s << indent << "ang_vel_deg: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.ang_vel_deg);
    s << indent << "ang_accel_rad: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.ang_accel_rad);
    s << indent << "ang_accel_deg: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.ang_accel_deg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CABIN_MSGS_MESSAGE_IMU_H
