// Generated by gencpp from file cabin_msgs/LinearCommand.msg
// DO NOT EDIT!


#ifndef CABIN_MSGS_MESSAGE_LINEARCOMMAND_H
#define CABIN_MSGS_MESSAGE_LINEARCOMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cabin_msgs
{
template <class ContainerAllocator>
struct LinearCommand_
{
  typedef LinearCommand_<ContainerAllocator> Type;

  LinearCommand_()
    : value(0.0)
    , mode(0)  {
    }
  LinearCommand_(const ContainerAllocator& _alloc)
    : value(0.0)
    , mode(0)  {
  (void)_alloc;
    }



   typedef float _value_type;
  _value_type value;

   typedef int8_t _mode_type;
  _mode_type mode;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(VELOCITY)
  #undef VELOCITY
#endif
#if defined(_WIN32) && defined(FORCE)
  #undef FORCE
#endif

  enum {
    VELOCITY = 1,
    FORCE = 0,
  };


  typedef boost::shared_ptr< ::cabin_msgs::LinearCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cabin_msgs::LinearCommand_<ContainerAllocator> const> ConstPtr;

}; // struct LinearCommand_

typedef ::cabin_msgs::LinearCommand_<std::allocator<void> > LinearCommand;

typedef boost::shared_ptr< ::cabin_msgs::LinearCommand > LinearCommandPtr;
typedef boost::shared_ptr< ::cabin_msgs::LinearCommand const> LinearCommandConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cabin_msgs::LinearCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cabin_msgs::LinearCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cabin_msgs::LinearCommand_<ContainerAllocator1> & lhs, const ::cabin_msgs::LinearCommand_<ContainerAllocator2> & rhs)
{
  return lhs.value == rhs.value &&
    lhs.mode == rhs.mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cabin_msgs::LinearCommand_<ContainerAllocator1> & lhs, const ::cabin_msgs::LinearCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cabin_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cabin_msgs::LinearCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cabin_msgs::LinearCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cabin_msgs::LinearCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cabin_msgs::LinearCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cabin_msgs::LinearCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cabin_msgs::LinearCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cabin_msgs::LinearCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0830fd9c68aca30cda146485fe7a06e0";
  }

  static const char* value(const ::cabin_msgs::LinearCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0830fd9c68aca30cULL;
  static const uint64_t static_value2 = 0xda146485fe7a06e0ULL;
};

template<class ContainerAllocator>
struct DataType< ::cabin_msgs::LinearCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cabin_msgs/LinearCommand";
  }

  static const char* value(const ::cabin_msgs::LinearCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cabin_msgs::LinearCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 value\n"
"int8 mode\n"
"\n"
"int8 VELOCITY=1\n"
"int8 FORCE=0\n"
;
  }

  static const char* value(const ::cabin_msgs::LinearCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cabin_msgs::LinearCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.value);
      stream.next(m.mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LinearCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cabin_msgs::LinearCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cabin_msgs::LinearCommand_<ContainerAllocator>& v)
  {
    s << indent << "value: ";
    Printer<float>::stream(s, indent + "  ", v.value);
    s << indent << "mode: ";
    Printer<int8_t>::stream(s, indent + "  ", v.mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CABIN_MSGS_MESSAGE_LINEARCOMMAND_H
