// Generated by gencpp from file cabin_msgs/NetLoad.msg
// DO NOT EDIT!


#ifndef CABIN_MSGS_MESSAGE_NETLOAD_H
#define CABIN_MSGS_MESSAGE_NETLOAD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace cabin_msgs
{
template <class ContainerAllocator>
struct NetLoad_
{
  typedef NetLoad_<ContainerAllocator> Type;

  NetLoad_()
    : header()
    , force()
    , moment()  {
    }
  NetLoad_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , force(_alloc)
    , moment(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _force_type;
  _force_type force;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _moment_type;
  _moment_type moment;





  typedef boost::shared_ptr< ::cabin_msgs::NetLoad_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cabin_msgs::NetLoad_<ContainerAllocator> const> ConstPtr;

}; // struct NetLoad_

typedef ::cabin_msgs::NetLoad_<std::allocator<void> > NetLoad;

typedef boost::shared_ptr< ::cabin_msgs::NetLoad > NetLoadPtr;
typedef boost::shared_ptr< ::cabin_msgs::NetLoad const> NetLoadConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cabin_msgs::NetLoad_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cabin_msgs::NetLoad_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cabin_msgs::NetLoad_<ContainerAllocator1> & lhs, const ::cabin_msgs::NetLoad_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.force == rhs.force &&
    lhs.moment == rhs.moment;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cabin_msgs::NetLoad_<ContainerAllocator1> & lhs, const ::cabin_msgs::NetLoad_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cabin_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cabin_msgs::NetLoad_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cabin_msgs::NetLoad_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cabin_msgs::NetLoad_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cabin_msgs::NetLoad_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cabin_msgs::NetLoad_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cabin_msgs::NetLoad_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cabin_msgs::NetLoad_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e2834aa33a3124031ca98bfb17a3484b";
  }

  static const char* value(const ::cabin_msgs::NetLoad_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe2834aa33a312403ULL;
  static const uint64_t static_value2 = 0x1ca98bfb17a3484bULL;
};

template<class ContainerAllocator>
struct DataType< ::cabin_msgs::NetLoad_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cabin_msgs/NetLoad";
  }

  static const char* value(const ::cabin_msgs::NetLoad_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cabin_msgs::NetLoad_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"geometry_msgs/Vector3 force\n"
"geometry_msgs/Vector3 moment\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::cabin_msgs::NetLoad_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cabin_msgs::NetLoad_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.force);
      stream.next(m.moment);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NetLoad_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cabin_msgs::NetLoad_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cabin_msgs::NetLoad_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "force: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.force);
    s << indent << "moment: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.moment);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CABIN_MSGS_MESSAGE_NETLOAD_H
