// Generated by gencpp from file cabin_msgs/Pwm.msg
// DO NOT EDIT!


#ifndef CABIN_MSGS_MESSAGE_PWM_H
#define CABIN_MSGS_MESSAGE_PWM_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cabin_msgs
{
template <class ContainerAllocator>
struct Pwm_
{
  typedef Pwm_<ContainerAllocator> Type;

  Pwm_()
    : vector_port_fwd(0)
    , vector_stbd_fwd(0)
    , vector_port_aft(0)
    , vector_stbd_aft(0)
    , heave_port_fwd(0)
    , heave_stbd_fwd(0)
    , heave_port_aft(0)
    , heave_stbd_aft(0)  {
    }
  Pwm_(const ContainerAllocator& _alloc)
    : vector_port_fwd(0)
    , vector_stbd_fwd(0)
    , vector_port_aft(0)
    , vector_stbd_aft(0)
    , heave_port_fwd(0)
    , heave_stbd_fwd(0)
    , heave_port_aft(0)
    , heave_stbd_aft(0)  {
  (void)_alloc;
    }



   typedef int16_t _vector_port_fwd_type;
  _vector_port_fwd_type vector_port_fwd;

   typedef int16_t _vector_stbd_fwd_type;
  _vector_stbd_fwd_type vector_stbd_fwd;

   typedef int16_t _vector_port_aft_type;
  _vector_port_aft_type vector_port_aft;

   typedef int16_t _vector_stbd_aft_type;
  _vector_stbd_aft_type vector_stbd_aft;

   typedef int16_t _heave_port_fwd_type;
  _heave_port_fwd_type heave_port_fwd;

   typedef int16_t _heave_stbd_fwd_type;
  _heave_stbd_fwd_type heave_stbd_fwd;

   typedef int16_t _heave_port_aft_type;
  _heave_port_aft_type heave_port_aft;

   typedef int16_t _heave_stbd_aft_type;
  _heave_stbd_aft_type heave_stbd_aft;





  typedef boost::shared_ptr< ::cabin_msgs::Pwm_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cabin_msgs::Pwm_<ContainerAllocator> const> ConstPtr;

}; // struct Pwm_

typedef ::cabin_msgs::Pwm_<std::allocator<void> > Pwm;

typedef boost::shared_ptr< ::cabin_msgs::Pwm > PwmPtr;
typedef boost::shared_ptr< ::cabin_msgs::Pwm const> PwmConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cabin_msgs::Pwm_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cabin_msgs::Pwm_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cabin_msgs::Pwm_<ContainerAllocator1> & lhs, const ::cabin_msgs::Pwm_<ContainerAllocator2> & rhs)
{
  return lhs.vector_port_fwd == rhs.vector_port_fwd &&
    lhs.vector_stbd_fwd == rhs.vector_stbd_fwd &&
    lhs.vector_port_aft == rhs.vector_port_aft &&
    lhs.vector_stbd_aft == rhs.vector_stbd_aft &&
    lhs.heave_port_fwd == rhs.heave_port_fwd &&
    lhs.heave_stbd_fwd == rhs.heave_stbd_fwd &&
    lhs.heave_port_aft == rhs.heave_port_aft &&
    lhs.heave_stbd_aft == rhs.heave_stbd_aft;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cabin_msgs::Pwm_<ContainerAllocator1> & lhs, const ::cabin_msgs::Pwm_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cabin_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cabin_msgs::Pwm_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cabin_msgs::Pwm_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cabin_msgs::Pwm_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cabin_msgs::Pwm_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cabin_msgs::Pwm_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cabin_msgs::Pwm_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cabin_msgs::Pwm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b5d8813cdee7d86a517feb4e60f361bf";
  }

  static const char* value(const ::cabin_msgs::Pwm_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb5d8813cdee7d86aULL;
  static const uint64_t static_value2 = 0x517feb4e60f361bfULL;
};

template<class ContainerAllocator>
struct DataType< ::cabin_msgs::Pwm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cabin_msgs/Pwm";
  }

  static const char* value(const ::cabin_msgs::Pwm_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cabin_msgs::Pwm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 vector_port_fwd\n"
"int16 vector_stbd_fwd\n"
"int16 vector_port_aft\n"
"int16 vector_stbd_aft\n"
"int16 heave_port_fwd\n"
"int16 heave_stbd_fwd\n"
"int16 heave_port_aft\n"
"int16 heave_stbd_aft\n"
;
  }

  static const char* value(const ::cabin_msgs::Pwm_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cabin_msgs::Pwm_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vector_port_fwd);
      stream.next(m.vector_stbd_fwd);
      stream.next(m.vector_port_aft);
      stream.next(m.vector_stbd_aft);
      stream.next(m.heave_port_fwd);
      stream.next(m.heave_stbd_fwd);
      stream.next(m.heave_port_aft);
      stream.next(m.heave_stbd_aft);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Pwm_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cabin_msgs::Pwm_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cabin_msgs::Pwm_<ContainerAllocator>& v)
  {
    s << indent << "vector_port_fwd: ";
    Printer<int16_t>::stream(s, indent + "  ", v.vector_port_fwd);
    s << indent << "vector_stbd_fwd: ";
    Printer<int16_t>::stream(s, indent + "  ", v.vector_stbd_fwd);
    s << indent << "vector_port_aft: ";
    Printer<int16_t>::stream(s, indent + "  ", v.vector_port_aft);
    s << indent << "vector_stbd_aft: ";
    Printer<int16_t>::stream(s, indent + "  ", v.vector_stbd_aft);
    s << indent << "heave_port_fwd: ";
    Printer<int16_t>::stream(s, indent + "  ", v.heave_port_fwd);
    s << indent << "heave_stbd_fwd: ";
    Printer<int16_t>::stream(s, indent + "  ", v.heave_stbd_fwd);
    s << indent << "heave_port_aft: ";
    Printer<int16_t>::stream(s, indent + "  ", v.heave_port_aft);
    s << indent << "heave_stbd_aft: ";
    Printer<int16_t>::stream(s, indent + "  ", v.heave_stbd_aft);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CABIN_MSGS_MESSAGE_PWM_H
