// Generated by gencpp from file cabin_msgs/PwmStamped.msg
// DO NOT EDIT!


#ifndef CABIN_MSGS_MESSAGE_PWMSTAMPED_H
#define CABIN_MSGS_MESSAGE_PWMSTAMPED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <cabin_msgs/Pwm.h>

namespace cabin_msgs
{
template <class ContainerAllocator>
struct PwmStamped_
{
  typedef PwmStamped_<ContainerAllocator> Type;

  PwmStamped_()
    : header()
    , pwm()  {
    }
  PwmStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , pwm(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::cabin_msgs::Pwm_<ContainerAllocator>  _pwm_type;
  _pwm_type pwm;





  typedef boost::shared_ptr< ::cabin_msgs::PwmStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cabin_msgs::PwmStamped_<ContainerAllocator> const> ConstPtr;

}; // struct PwmStamped_

typedef ::cabin_msgs::PwmStamped_<std::allocator<void> > PwmStamped;

typedef boost::shared_ptr< ::cabin_msgs::PwmStamped > PwmStampedPtr;
typedef boost::shared_ptr< ::cabin_msgs::PwmStamped const> PwmStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cabin_msgs::PwmStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cabin_msgs::PwmStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cabin_msgs::PwmStamped_<ContainerAllocator1> & lhs, const ::cabin_msgs::PwmStamped_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.pwm == rhs.pwm;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cabin_msgs::PwmStamped_<ContainerAllocator1> & lhs, const ::cabin_msgs::PwmStamped_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cabin_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cabin_msgs::PwmStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cabin_msgs::PwmStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cabin_msgs::PwmStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cabin_msgs::PwmStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cabin_msgs::PwmStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cabin_msgs::PwmStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cabin_msgs::PwmStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "91277acb39d0060faa9fbcfd2d1a7b92";
  }

  static const char* value(const ::cabin_msgs::PwmStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x91277acb39d0060fULL;
  static const uint64_t static_value2 = 0xaa9fbcfd2d1a7b92ULL;
};

template<class ContainerAllocator>
struct DataType< ::cabin_msgs::PwmStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cabin_msgs/PwmStamped";
  }

  static const char* value(const ::cabin_msgs::PwmStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cabin_msgs::PwmStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"Pwm pwm\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: cabin_msgs/Pwm\n"
"int16 vector_port_fwd\n"
"int16 vector_stbd_fwd\n"
"int16 vector_port_aft\n"
"int16 vector_stbd_aft\n"
"int16 heave_port_fwd\n"
"int16 heave_stbd_fwd\n"
"int16 heave_port_aft\n"
"int16 heave_stbd_aft\n"
;
  }

  static const char* value(const ::cabin_msgs::PwmStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cabin_msgs::PwmStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.pwm);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PwmStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cabin_msgs::PwmStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cabin_msgs::PwmStamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "pwm: ";
    s << std::endl;
    Printer< ::cabin_msgs::Pwm_<ContainerAllocator> >::stream(s, indent + "  ", v.pwm);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CABIN_MSGS_MESSAGE_PWMSTAMPED_H
