// Generated by gencpp from file cabin_msgs/ResetControls.msg
// DO NOT EDIT!


#ifndef CABIN_MSGS_MESSAGE_RESETCONTROLS_H
#define CABIN_MSGS_MESSAGE_RESETCONTROLS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cabin_msgs
{
template <class ContainerAllocator>
struct ResetControls_
{
  typedef ResetControls_<ContainerAllocator> Type;

  ResetControls_()
    : reset_pwm(false)  {
    }
  ResetControls_(const ContainerAllocator& _alloc)
    : reset_pwm(false)  {
  (void)_alloc;
    }



   typedef uint8_t _reset_pwm_type;
  _reset_pwm_type reset_pwm;





  typedef boost::shared_ptr< ::cabin_msgs::ResetControls_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cabin_msgs::ResetControls_<ContainerAllocator> const> ConstPtr;

}; // struct ResetControls_

typedef ::cabin_msgs::ResetControls_<std::allocator<void> > ResetControls;

typedef boost::shared_ptr< ::cabin_msgs::ResetControls > ResetControlsPtr;
typedef boost::shared_ptr< ::cabin_msgs::ResetControls const> ResetControlsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cabin_msgs::ResetControls_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cabin_msgs::ResetControls_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cabin_msgs::ResetControls_<ContainerAllocator1> & lhs, const ::cabin_msgs::ResetControls_<ContainerAllocator2> & rhs)
{
  return lhs.reset_pwm == rhs.reset_pwm;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cabin_msgs::ResetControls_<ContainerAllocator1> & lhs, const ::cabin_msgs::ResetControls_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cabin_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cabin_msgs::ResetControls_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cabin_msgs::ResetControls_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cabin_msgs::ResetControls_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cabin_msgs::ResetControls_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cabin_msgs::ResetControls_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cabin_msgs::ResetControls_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cabin_msgs::ResetControls_<ContainerAllocator> >
{
  static const char* value()
  {
    return "702d2e5e556f108c9934abfa9d285486";
  }

  static const char* value(const ::cabin_msgs::ResetControls_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x702d2e5e556f108cULL;
  static const uint64_t static_value2 = 0x9934abfa9d285486ULL;
};

template<class ContainerAllocator>
struct DataType< ::cabin_msgs::ResetControls_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cabin_msgs/ResetControls";
  }

  static const char* value(const ::cabin_msgs::ResetControls_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cabin_msgs::ResetControls_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool reset_pwm\n"
;
  }

  static const char* value(const ::cabin_msgs::ResetControls_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cabin_msgs::ResetControls_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.reset_pwm);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ResetControls_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cabin_msgs::ResetControls_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cabin_msgs::ResetControls_<ContainerAllocator>& v)
  {
    s << indent << "reset_pwm: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.reset_pwm);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CABIN_MSGS_MESSAGE_RESETCONTROLS_H
