// Generated by gencpp from file cabin_msgs/SwitchState.msg
// DO NOT EDIT!


#ifndef CABIN_MSGS_MESSAGE_SWITCHSTATE_H
#define CABIN_MSGS_MESSAGE_SWITCHSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace cabin_msgs
{
template <class ContainerAllocator>
struct SwitchState_
{
  typedef SwitchState_<ContainerAllocator> Type;

  SwitchState_()
    : header()
    , kill(false)
    , sw1(false)
    , sw2(false)
    , sw3(false)
    , sw4(false)
    , sw5(false)  {
    }
  SwitchState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , kill(false)
    , sw1(false)
    , sw2(false)
    , sw3(false)
    , sw4(false)
    , sw5(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _kill_type;
  _kill_type kill;

   typedef uint8_t _sw1_type;
  _sw1_type sw1;

   typedef uint8_t _sw2_type;
  _sw2_type sw2;

   typedef uint8_t _sw3_type;
  _sw3_type sw3;

   typedef uint8_t _sw4_type;
  _sw4_type sw4;

   typedef uint8_t _sw5_type;
  _sw5_type sw5;





  typedef boost::shared_ptr< ::cabin_msgs::SwitchState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cabin_msgs::SwitchState_<ContainerAllocator> const> ConstPtr;

}; // struct SwitchState_

typedef ::cabin_msgs::SwitchState_<std::allocator<void> > SwitchState;

typedef boost::shared_ptr< ::cabin_msgs::SwitchState > SwitchStatePtr;
typedef boost::shared_ptr< ::cabin_msgs::SwitchState const> SwitchStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cabin_msgs::SwitchState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cabin_msgs::SwitchState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cabin_msgs::SwitchState_<ContainerAllocator1> & lhs, const ::cabin_msgs::SwitchState_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.kill == rhs.kill &&
    lhs.sw1 == rhs.sw1 &&
    lhs.sw2 == rhs.sw2 &&
    lhs.sw3 == rhs.sw3 &&
    lhs.sw4 == rhs.sw4 &&
    lhs.sw5 == rhs.sw5;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cabin_msgs::SwitchState_<ContainerAllocator1> & lhs, const ::cabin_msgs::SwitchState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cabin_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cabin_msgs::SwitchState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cabin_msgs::SwitchState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cabin_msgs::SwitchState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cabin_msgs::SwitchState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cabin_msgs::SwitchState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cabin_msgs::SwitchState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cabin_msgs::SwitchState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e79bdc65259745272013ea9f210e90fb";
  }

  static const char* value(const ::cabin_msgs::SwitchState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe79bdc6525974527ULL;
  static const uint64_t static_value2 = 0x2013ea9f210e90fbULL;
};

template<class ContainerAllocator>
struct DataType< ::cabin_msgs::SwitchState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cabin_msgs/SwitchState";
  }

  static const char* value(const ::cabin_msgs::SwitchState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cabin_msgs::SwitchState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"bool kill\n"
"bool sw1\n"
"bool sw2\n"
"bool sw3\n"
"bool sw4\n"
"bool sw5\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::cabin_msgs::SwitchState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cabin_msgs::SwitchState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.kill);
      stream.next(m.sw1);
      stream.next(m.sw2);
      stream.next(m.sw3);
      stream.next(m.sw4);
      stream.next(m.sw5);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SwitchState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cabin_msgs::SwitchState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cabin_msgs::SwitchState_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "kill: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.kill);
    s << indent << "sw1: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sw1);
    s << indent << "sw2: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sw2);
    s << indent << "sw3: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sw3);
    s << indent << "sw4: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sw4);
    s << indent << "sw5: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sw5);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CABIN_MSGS_MESSAGE_SWITCHSTATE_H
