// Generated by gencpp from file cabin_msgs/ThrustStamped.msg
// DO NOT EDIT!


#ifndef CABIN_MSGS_MESSAGE_THRUSTSTAMPED_H
#define CABIN_MSGS_MESSAGE_THRUSTSTAMPED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <cabin_msgs/Thrust.h>

namespace cabin_msgs
{
template <class ContainerAllocator>
struct ThrustStamped_
{
  typedef ThrustStamped_<ContainerAllocator> Type;

  ThrustStamped_()
    : header()
    , force()  {
    }
  ThrustStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , force(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::cabin_msgs::Thrust_<ContainerAllocator>  _force_type;
  _force_type force;





  typedef boost::shared_ptr< ::cabin_msgs::ThrustStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cabin_msgs::ThrustStamped_<ContainerAllocator> const> ConstPtr;

}; // struct ThrustStamped_

typedef ::cabin_msgs::ThrustStamped_<std::allocator<void> > ThrustStamped;

typedef boost::shared_ptr< ::cabin_msgs::ThrustStamped > ThrustStampedPtr;
typedef boost::shared_ptr< ::cabin_msgs::ThrustStamped const> ThrustStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cabin_msgs::ThrustStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cabin_msgs::ThrustStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cabin_msgs::ThrustStamped_<ContainerAllocator1> & lhs, const ::cabin_msgs::ThrustStamped_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.force == rhs.force;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cabin_msgs::ThrustStamped_<ContainerAllocator1> & lhs, const ::cabin_msgs::ThrustStamped_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cabin_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cabin_msgs::ThrustStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cabin_msgs::ThrustStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cabin_msgs::ThrustStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cabin_msgs::ThrustStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cabin_msgs::ThrustStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cabin_msgs::ThrustStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cabin_msgs::ThrustStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ee14a54448c6e489e47b8a0a9c83e2dc";
  }

  static const char* value(const ::cabin_msgs::ThrustStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xee14a54448c6e489ULL;
  static const uint64_t static_value2 = 0xe47b8a0a9c83e2dcULL;
};

template<class ContainerAllocator>
struct DataType< ::cabin_msgs::ThrustStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cabin_msgs/ThrustStamped";
  }

  static const char* value(const ::cabin_msgs::ThrustStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cabin_msgs::ThrustStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"Thrust force\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: cabin_msgs/Thrust\n"
"float32 vector_port_fwd\n"
"float32 vector_stbd_fwd\n"
"float32 vector_port_aft\n"
"float32 vector_stbd_aft\n"
"float32 heave_port_fwd\n"
"float32 heave_stbd_fwd\n"
"float32 heave_port_aft\n"
"float32 heave_stbd_aft\n"
"\n"
"# Used to index controllers within the pwm controller\n"
"int8 VPF = 0\n"
"int8 VSF = 1\n"
"int8 VPA = 2\n"
"int8 VSA = 3\n"
"int8 HPF = 4\n"
"int8 HSF = 5\n"
"int8 HPA = 6\n"
"int8 HSA = 7\n"
;
  }

  static const char* value(const ::cabin_msgs::ThrustStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cabin_msgs::ThrustStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.force);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ThrustStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cabin_msgs::ThrustStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cabin_msgs::ThrustStamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "force: ";
    s << std::endl;
    Printer< ::cabin_msgs::Thrust_<ContainerAllocator> >::stream(s, indent + "  ", v.force);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CABIN_MSGS_MESSAGE_THRUSTSTAMPED_H
