// Generated by gencpp from file cabin_msgs/Thrust.msg
// DO NOT EDIT!


#ifndef CABIN_MSGS_MESSAGE_THRUST_H
#define CABIN_MSGS_MESSAGE_THRUST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cabin_msgs
{
template <class ContainerAllocator>
struct Thrust_
{
  typedef Thrust_<ContainerAllocator> Type;

  Thrust_()
    : vector_port_fwd(0.0)
    , vector_stbd_fwd(0.0)
    , vector_port_aft(0.0)
    , vector_stbd_aft(0.0)
    , heave_port_fwd(0.0)
    , heave_stbd_fwd(0.0)
    , heave_port_aft(0.0)
    , heave_stbd_aft(0.0)  {
    }
  Thrust_(const ContainerAllocator& _alloc)
    : vector_port_fwd(0.0)
    , vector_stbd_fwd(0.0)
    , vector_port_aft(0.0)
    , vector_stbd_aft(0.0)
    , heave_port_fwd(0.0)
    , heave_stbd_fwd(0.0)
    , heave_port_aft(0.0)
    , heave_stbd_aft(0.0)  {
  (void)_alloc;
    }



   typedef float _vector_port_fwd_type;
  _vector_port_fwd_type vector_port_fwd;

   typedef float _vector_stbd_fwd_type;
  _vector_stbd_fwd_type vector_stbd_fwd;

   typedef float _vector_port_aft_type;
  _vector_port_aft_type vector_port_aft;

   typedef float _vector_stbd_aft_type;
  _vector_stbd_aft_type vector_stbd_aft;

   typedef float _heave_port_fwd_type;
  _heave_port_fwd_type heave_port_fwd;

   typedef float _heave_stbd_fwd_type;
  _heave_stbd_fwd_type heave_stbd_fwd;

   typedef float _heave_port_aft_type;
  _heave_port_aft_type heave_port_aft;

   typedef float _heave_stbd_aft_type;
  _heave_stbd_aft_type heave_stbd_aft;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(VPF)
  #undef VPF
#endif
#if defined(_WIN32) && defined(VSF)
  #undef VSF
#endif
#if defined(_WIN32) && defined(VPA)
  #undef VPA
#endif
#if defined(_WIN32) && defined(VSA)
  #undef VSA
#endif
#if defined(_WIN32) && defined(HPF)
  #undef HPF
#endif
#if defined(_WIN32) && defined(HSF)
  #undef HSF
#endif
#if defined(_WIN32) && defined(HPA)
  #undef HPA
#endif
#if defined(_WIN32) && defined(HSA)
  #undef HSA
#endif

  enum {
    VPF = 0,
    VSF = 1,
    VPA = 2,
    VSA = 3,
    HPF = 4,
    HSF = 5,
    HPA = 6,
    HSA = 7,
  };


  typedef boost::shared_ptr< ::cabin_msgs::Thrust_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cabin_msgs::Thrust_<ContainerAllocator> const> ConstPtr;

}; // struct Thrust_

typedef ::cabin_msgs::Thrust_<std::allocator<void> > Thrust;

typedef boost::shared_ptr< ::cabin_msgs::Thrust > ThrustPtr;
typedef boost::shared_ptr< ::cabin_msgs::Thrust const> ThrustConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cabin_msgs::Thrust_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cabin_msgs::Thrust_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cabin_msgs::Thrust_<ContainerAllocator1> & lhs, const ::cabin_msgs::Thrust_<ContainerAllocator2> & rhs)
{
  return lhs.vector_port_fwd == rhs.vector_port_fwd &&
    lhs.vector_stbd_fwd == rhs.vector_stbd_fwd &&
    lhs.vector_port_aft == rhs.vector_port_aft &&
    lhs.vector_stbd_aft == rhs.vector_stbd_aft &&
    lhs.heave_port_fwd == rhs.heave_port_fwd &&
    lhs.heave_stbd_fwd == rhs.heave_stbd_fwd &&
    lhs.heave_port_aft == rhs.heave_port_aft &&
    lhs.heave_stbd_aft == rhs.heave_stbd_aft;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cabin_msgs::Thrust_<ContainerAllocator1> & lhs, const ::cabin_msgs::Thrust_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cabin_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cabin_msgs::Thrust_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cabin_msgs::Thrust_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cabin_msgs::Thrust_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cabin_msgs::Thrust_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cabin_msgs::Thrust_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cabin_msgs::Thrust_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cabin_msgs::Thrust_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b32a790aa38ecc6d0210e752292519c8";
  }

  static const char* value(const ::cabin_msgs::Thrust_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb32a790aa38ecc6dULL;
  static const uint64_t static_value2 = 0x0210e752292519c8ULL;
};

template<class ContainerAllocator>
struct DataType< ::cabin_msgs::Thrust_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cabin_msgs/Thrust";
  }

  static const char* value(const ::cabin_msgs::Thrust_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cabin_msgs::Thrust_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 vector_port_fwd\n"
"float32 vector_stbd_fwd\n"
"float32 vector_port_aft\n"
"float32 vector_stbd_aft\n"
"float32 heave_port_fwd\n"
"float32 heave_stbd_fwd\n"
"float32 heave_port_aft\n"
"float32 heave_stbd_aft\n"
"\n"
"# Used to index controllers within the pwm controller\n"
"int8 VPF = 0\n"
"int8 VSF = 1\n"
"int8 VPA = 2\n"
"int8 VSA = 3\n"
"int8 HPF = 4\n"
"int8 HSF = 5\n"
"int8 HPA = 6\n"
"int8 HSA = 7\n"
;
  }

  static const char* value(const ::cabin_msgs::Thrust_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cabin_msgs::Thrust_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vector_port_fwd);
      stream.next(m.vector_stbd_fwd);
      stream.next(m.vector_port_aft);
      stream.next(m.vector_stbd_aft);
      stream.next(m.heave_port_fwd);
      stream.next(m.heave_stbd_fwd);
      stream.next(m.heave_port_aft);
      stream.next(m.heave_stbd_aft);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Thrust_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cabin_msgs::Thrust_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cabin_msgs::Thrust_<ContainerAllocator>& v)
  {
    s << indent << "vector_port_fwd: ";
    Printer<float>::stream(s, indent + "  ", v.vector_port_fwd);
    s << indent << "vector_stbd_fwd: ";
    Printer<float>::stream(s, indent + "  ", v.vector_stbd_fwd);
    s << indent << "vector_port_aft: ";
    Printer<float>::stream(s, indent + "  ", v.vector_port_aft);
    s << indent << "vector_stbd_aft: ";
    Printer<float>::stream(s, indent + "  ", v.vector_stbd_aft);
    s << indent << "heave_port_fwd: ";
    Printer<float>::stream(s, indent + "  ", v.heave_port_fwd);
    s << indent << "heave_stbd_fwd: ";
    Printer<float>::stream(s, indent + "  ", v.heave_stbd_fwd);
    s << indent << "heave_port_aft: ";
    Printer<float>::stream(s, indent + "  ", v.heave_port_aft);
    s << indent << "heave_stbd_aft: ";
    Printer<float>::stream(s, indent + "  ", v.heave_stbd_aft);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CABIN_MSGS_MESSAGE_THRUST_H
